#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define CANTIDAD_MAXIMA_JUGADORES 6
#define CANTIDAD_INICIAL_EJERCITOS_POR_TERRITORIO 1
#define DIGITOS_MEDIDA_DEL_PAQUETE 8

#define MILISEGUNDOS_POOLEO_ORDEN 50
#define MILISEGUNDOS_POOLEO_ENVIO_MENSAJE 50
#define MILISEGUNDOS_POOLEO_RECEPCION_ORDEN 50

#endif /* CONSTANTES_H_ */
